In [44]:
import numpy as np

In [46]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)

In [47]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [48]:
x2

array([0., 1., 2.])

In [49]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [55]:
A = np.zeros((3,2,2))
A[0] = np.eye(2) * 2
A[1] = np.eye(2) * 3
A[2] = np.eye(2) * 4

In [52]:
b = np.random.standard_normal((3,2))

In [62]:
b = b.T

In [64]:
b

array([[-1.59385877,  0.84117081, -0.36703103],
       [ 0.22190939,  0.06257329, -1.43165102]])

In [56]:
A

array([[[2., 0.],
        [0., 2.]],

       [[3., 0.],
        [0., 3.]],

       [[4., 0.],
        [0., 4.]]])

In [63]:
np.einsum('...ij,j...->i...', A, b)

array([[-3.18771755,  2.52351244, -1.46812412],
       [ 0.44381877,  0.18771987, -5.72660406]])

In [67]:
A = np.ones(3)
B = np.ones(2)

In [69]:
np.array_equal(A, B)

False

In [70]:
a = np.array([2,3])
0.1**a


array([0.01 , 0.001])

In [77]:
np.array([[2,3,1], [4,5,1]]) * (0.1**a)[:,None]

array([[0.02 , 0.03 , 0.01 ],
       [0.004, 0.005, 0.001]])